apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-wi
  namespace: demo
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "02caeb31-d80e-44b9-a8be-5cdad6fcc91d"
    keyvaultName: "minakv20260319"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: app-secret
          objectType: secret
          objectVersion: ""
    tenantId: "c3442cc0-f81b-4407-9b56-ca1ce6c1340c"
